[package]
name = "ru-yew-app1"
version = "0.1.0"
edition = "2021"

[dependencies]
yew = { version="0.21", features=["csr"] }
wasm-bindgen = "0.2"
serde = "1"
serde_derive = "1"
web-sys = { version = "0.3", features = ["HtmlInputElement","HtmlSelectElement","Window"] }
yew-router = "0.18"
